CREATE TABLE SAMOCHODY (
	VIN CHAR(17) CHECK (LENGTH (VIN) = 17), 
	NR_TABLICY VARCHAR, 
	MARKA VARCHAR(20), 
	ROCZNIK INT(4),
	PRZEBIEG INT,
	KOLOR VARCHAR
);
CREATE TABLE WYSTAWIONE(
	PESEL INT(11) CHECK (LENGTH (PESEL) = 11),
	VIN CHAR(17) CHECK (LENGTH (VIN) = 17)
);
CREATE TABLE SPRZEDALI(
	IMIE VARCHAR(20),
	NAZWISKO VARCHAR(20),
	PESEL INT(11) CHECK (LENGTH (PESEL) = 11),
	ULICA VARCHAR,
	KOD_POCZTOWY CHAR,
	MIASTO VARCHAR
);
CREATE TABLE SPRZEDANE(
	PESEL INT(11) CHECK (LENGTH (PESEL) = 11),
	VIN CHAR(17) CHECK (LENGTH (VIN) = 17)
);
CREATE TABLE KUPILI(
	IMIE VARCHAR(20),
	NAZWISKO VARCHAR(20),
	PESEL INT(11) CHECK (LENGTH (PESEL) = 11),
	ULICA VARCHAR,
	KOD_POCZTOWY CHAR,
	MIASTO VARCHAR
)
					  