CREATE TABLE SAMOCHODY (
	VIN INT, 
	NR_TABLICY VARCHAR, 
	MARKA VARCHAR, 
	ROCZNIK INT,
	PRZEBIEG INT,
	KOLOR VARCHAR
);
CREATE TABLE WYSTAWIONE(
	PESEL INT,
	VIN INT
);
CREATE TABLE SPRZEDALI(
	IMIE VARCHAR,
	NAZWISKO VARCHAR,
	PESEL INT,
	ULICA VARCHAR,
	KOD_POCZTOWY CHAR,
	MIASTO VARCHAR
);
CREATE TABLE SPRZEDANE(
	PESEL INT,
	VIN INT
);
CREATE TABLE KUPILI(
	IMIE VARCHAR,
	NAZWISKO VARCHAR,
	PESEL INT,
	ULICA VARCHAR,
	KOD_POCZTOWY CHAR,
	MIASTO VARCHAR
)
					  